# Generated by Django 3.2.23 on 2023-12-27 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sns', '0002_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='share_id',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Prifile_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_text_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
