# Generated by Django 3.2.23 on 2023-12-27 16:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sns', '0003_auto_20231227_1610'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prifile_text',
            new_name='Profile_text',
        ),
    ]
