# Generated by Django 3.2.23 on 2023-12-28 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0004_rename_prifile_text_profile_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='message',
            name='group',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
